#!/bin/bash

set -e

TARGET=/etc/nginx/sites-available/ble2json.conf

LINK_NAME=/etc/nginx/sites-enabled/ble2json.conf

if [[ -e $TARGET ]] && ! [[ -e $LINK_NAME ]] ; then
    ln -s $TARGET $LINK_NAME
fi

systemctl enable ble2json.service


